### ISSUE TITLE
Space in data directory path causes install failure

### ISSUE THREAD

**Issue by chadjaros** [vorburger/MariaDB4j#35]
using a base dir with a space, such as

    --datadir=/path/path with space/more-path

causes the install to fail. The path params should be properly quoted in order to handle this.

**Comment by chadjaros** [comment]
An appropriate fix can be applied at ManagedProcessBuilder.java:86

    public ManagedProcessBuilder addFileArgument(String arg, File file) throws IOException {
	return addArgument(arg + "=\"" + file.getCanonicalPath() + "\"");
    }

**Comment by chadjaros** [comment]
The fix is turning out to be more complicated than what I put above, but path arguments should generally be quoted.

**Comment by chadjaros** [comment]
I was able to get this far:
    
    /var/folders/8b/3c_7twb90lg_wcdldj47dcqh0000gq/T/MariaDB4j/base/bin/mysqld: Too many arguments (first extra is '"--datadir=/path with spaces"').
    160126 15:24:08 [ERROR] Aborting
    160126 15:24:08 [Note] /var/folders/8b/3c_7twb90lg_wcdldj47dcqh0000gq/T/MariaDB4j/base/bin/mysqld: Shutdown complete
	at ch.vorburger.exec.ManagedProcess.startAndWaitForConsoleMessageMaxMs(ManagedProcess.java:248)
	at ch.vorburger.mariadb4j.DB.start(DB.java:135)

by implementing the function:

    override ManagedProcessBuilder addFileArgument(String arg, File file) {
        String path = file.getCanonicalPath();
        if(path.contains(" ")) {
            commonsExecCommandLine.addArgument(arg + "=\"" + path + "\"", false);
        }
        else {
            commonsExecCommandLine.addArgument(arg + "=" + path);
        }
        return this;
    }

**Comment by vorburger** [comment]
@chadjaros thanks for your interest in this project. Sorry for my delay in responding - life happened.

I'm wondering which version you use - I thought I've already fixed exactly this problem in https://github.com/vorburger/MariaDB4j/issues/30 ? See also the ch.vorburger.mariadb4j.tests.MariaDB4jSampleOtherTest.dataDirWithSpace(). Or is this something else?? I hope you don't mind if I close this issue, assume it's a dupe. Shout if you disagree, and let's re-open in that case.

The version currently on jCenter does not include that yet - I'll try to deploy latest ASAP. You can manually build it from source and locally install it in the mean time, of course.

Do you use MariaDB4j at http://www.classkick.com ?  Just curious.

**Comment by john-dev** [comment]
Hey,

i know this thread is old - but i still experience "kind of" the same problem.
The database will not be created at the destination of dataDir if there is a space in the path, even tho it looks good in the executed command.
It does create the dataDir target, but it does not store the DB files inside it

ps output:
`/var/folders/x4/y9bt3_bs5gl3fl4ntvn0f51c0000gn/T/MariaDB4j/base/bin/mysqld --no-defaults --console --skip-grant-tables --max_allowed_packet=64M --basedir=/private/var/folders/x4/y9bt3_bs5gl3fl4ntvn0f51c0000gn/T/MariaDB4j/base --datadir="/Users/myUser/Workspace/Launcher/resources folder/db" --port=3306 --socket=/private/var/folders/x4/y9bt3_bs5gl3fl4ntvn0f51c0000gn/T/MariaDB4j.3306.sock`

if i execute it manually, everything is fine..


Any ideas?

**Comment by xipgroc** [comment]
This is not fixed, still investigating why, but I'm also experiencing the same issue. In windows only.

If datadir does not contain spaces, everything is OK. Is does create the datadir, installs just fine in it and executes normally.

If however the datadir does contain spaces, it first creates the datadir with no problems, then goes on to installation, finishes installation OK but on the wrong path (so if datadir path is, say "C:\Program Files\MyProgram\datadir", it will install datadir on "C:\Program"). Then it fails when executing mysqld with "Too many arguments (first extra is Files...".

All commands seem to be quoted just fine, so when executed in the console they don't give any error.
